UN-OCHA/ai-summarize-site

docker/Dockerfile
html/modules/custom/ocha_ai_summarize/ocha_ai_summarize.module
html/modules/custom/ocha_ai_summarize/src/Plugin/QueueWorker/OchaAiSummarizeExtractText.php

feat: Run everything obviously

---

config/imagemagick.settings.yml
config/user.settings.yml

chore: Update shipped config, so prod is the baseline.

---

config/core.extension.yml
config/language/fr/monitoring.sensor_config.ocha_deployment_identifier.yml
config/monitoring.sensor_config.core_maintenance_mode.yml
config/monitoring.sensor_config.core_requirements_memcache.yml
config/monitoring.sensor_config.core_requirements_mysql.yml
config/monitoring.sensor_config.core_requirements_system.yml
config/monitoring.sensor_config.dblog_image_missing_style.yml
config/monitoring.sensor_config.ocha_common_design.yml
config/monitoring.sensor_config.ocha_current_composer_version.yml
config/monitoring.sensor_config.ocha_current_drupal_version.yml
config/monitoring.sensor_config.ocha_current_php_version.yml
config/monitoring.sensor_config.ocha_current_release.yml
config/monitoring.sensor_config.ocha_env_link_fixer.yml
config/monitoring.sensor_config.ocha_google_tag.yml
config/monitoring.sensor_config.ocha_gtm_barebones.yml
config/monitoring.sensor_config.ocha_ocha_monitoring.yml
config/monitoring.sensor_config.ocha_un_date.yml
config/monitoring.sensor_config.user_sessions_all.yml
config/monitoring.sensor_config.user_sessions_authenticated.yml
config/views.view.my_documents.yml
html/modules/custom/ocha_ai_summarize/ocha_ai_summarize.links.menu.yml
html/modules/custom/ocha_ai_summarize/ocha_ai_summarize.module
html/modules/custom/ocha_ai_summarize/ocha_ai_summarize.routing.yml

feat: Home page

---

config/user.settings.yml

feat: Create account

---

composer.lock
config/views.view.my_documents.yml
html/modules/custom/ocha_ai_summarize/ocha_ai_summarize.services.yml
html/modules/custom/ocha_ai_summarize/src/EventSubscriber/AnonymousFrontpageSubscriber.php

feat: Separate home page

---

config/core.entity_view_display.node.action_points.default.yml
config/core.entity_view_display.node.summary.default.yml
config/field.field.node.action_points.field_ai_brain.yml
config/field.field.node.summary.field_ai_brain.yml
config/node.type.action_points.yml
html/modules/custom/ocha_ai_summarize/ocha_ai_summarize.module
html/modules/custom/ocha_ai_summarize/src/Plugin/QueueWorker/OchaAiSummarizeActionPoints.php
html/modules/custom/ocha_ai_summarize/src/Plugin/QueueWorker/OchaAiSummarizeSummarize.php
html/themes/custom/common_design_subtheme/css/styles.css
html/themes/custom/common_design_subtheme/templates/field/field--comment.html.twig

feat: Edit screen, comments, email

---

config/views.view.my_documents.yml

feat: Update wording

---

local/README.md
local/docker-compose.yml
local/shared/settings/services.yml
local/shared/settings/settings.local.php

Refs: development
Allows spinning up locally using the approach from https://github.com/UN-OCHA/local-reverse-proxy/

chore: add local setup

---

composer.json
config/monitoring.sensor_config.monitoring_installed_modules.yml

chore: remove remaining references to google_tag module

---

config/seckit.settings.yml

chore: allow google tracking

---

config/seckit.settings.yml
html/modules/custom/ocha_ai_summarize/src/Access/OchaAiSummarizeAccess.php

chore: remove ad domains from csp

---

.github/workflows/composer-update-config.yml
README.md
tests/docker-compose.yml

chore: include config changes in automatic updates

---

config/seckit.settings.yml

chore: add more google domains

---

PATCHES/user_expire-customize-notification-email.patch
PATCHES/user_expire-reset-expiration-on-reactivation.patch
composer.lock
config/monitoring.sensor_config.core_cron_last_run_age.yml
config/monitoring.sensor_config.monitoring_installed_modules.yml
config/monitoring.sensor_config.ocha_admin_paths.yml
config/monitoring.sensor_config.ocha_common_design.yml
config/monitoring.sensor_config.ocha_current_composer_version.yml
config/monitoring.sensor_config.ocha_current_drupal_version.yml
config/monitoring.sensor_config.ocha_current_php_version.yml
config/monitoring.sensor_config.ocha_current_release.yml
config/monitoring.sensor_config.ocha_deployment_identifier.yml
config/monitoring.sensor_config.ocha_env_link_fixer.yml
config/monitoring.sensor_config.ocha_gtm_barebones.yml
config/monitoring.sensor_config.ocha_ocha_monitoring.yml
config/monitoring.sensor_config.ocha_un_date.yml
config/monitoring.sensor_config.update_contrib.yml
config/monitoring.sensor_config.update_core.yml

chore: periodic updates including patches

---

config/core.entity_form_display.node.summary.default.yml
html/modules/custom/ocha_ai_summarize/ocha_ai_summarize.module

feat: Change wording when no summary is present

---

tests/vrt/urls_anon.txt

tests: add some urls for vrt

---

config/seckit.settings.yml

chore: csp restore data: as exception for img-src

---

composer.json
composer.lock
config/config_split.config_split.config_dev.yml

chore: remove unused module config_filter

---

config/core.extension.yml

chore: remove allowed_formats module and handle configuration

---

config/field.field.node.action_points.field_ai_brain.yml
config/field.field.node.summary.field_ai_brain.yml
config/field.storage.node.field_ai_brain.yml
html/modules/custom/ocha_ai_summarize/ocha_ai_summarize.module
html/modules/custom/ocha_ai_summarize/src/Plugin/QueueWorker/OchaAiSummarizeActionPoints.php
html/modules/custom/ocha_ai_summarize/src/Plugin/QueueWorker/OchaAiSummarizeExtractText.php
html/modules/custom/ocha_ai_summarize/src/Plugin/QueueWorker/OchaAiSummarizeSummarize.php

feat: Remove titan, add nova

---

CHANGELOG.md
composer.json
composer.lock

To allow merging https://github.com/UN-OCHA/ai-summarize-site/pull/199

Prepare deployment 21-02-2025
